import { Poppins } from 'next/font/google'

import '../styles/global.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const poppins = Poppins({
    weight: ['400', '500', '700', '900'],
    subsets: ['latin'] 
  })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
